### PR TITLE
Overhaul venue page with more info

### PR DESCRIPTION
**Pull request by bibliotechy**
Total overhaul of the venue page. Please have a look @hackmastera @sdellis @roastduckalamode and give me some feedbback.

Thanks

### CODE REVIEW

**Comment by queryluke** [comment]
@bibliotechy I like it. The only minor edits I could see (and I'm no designer).
1. Loose the odd "(1)" for the sheraton tel#. Either go to the standard "+1 " (note the space) or format like the chem-heritage/franklin numbers
2. And on that note, make all the phone numbers formatted the same way (the liberty service has slugs).
   IMHO, I like the slugs, with the leading +1 if we're worried about international callers. If you go with slugs the leading +1 should also have a slug "+1-555-777-0000"
3. Bump up the header levels for the "Getting to the hotel" section. The H5's get lost in the text.

**Comment by hackartisan** [comment]
It's great. Do we also want to put the reception venue info here?

**Comment by sdellis** [comment]
Checking it out now...

**Comment by bibliotechy** [comment]
@roastduckalamode Those all make sense. 

@hackmastera  Reception venue information does make sense.

**Comment by sdellis** [comment]
Ok, this is fine for now.  

However, I think these should be separate pages, kind of like the Schedule section.  Each has quite a bit of information associated with it (transportation/maps, floorplans, date/times, menus) that justify separate pages.  I have a busy day today (talking about the Code4Lib GitHub Pages project for that NISO webinar) but I can try to break these out later.

**Comment by bibliotechy** [comment]
Alright, I addressed the issues raised by @hackmastera and @roastduckalamode .

@sdellis I agree that stuff would be nice to have, but I wanted to make sure we had basic info for each place at the very least.

**Comment by sdellis** [comment]
@bibliotechy Definitely not a showstopper!  Thank you for doing this. I will look into breaking it up tomorrow or over the weekend.

**Pull request merged**
