### PR TITLE
two styles of displaying past speakers

### PR DESCRIPTION
**Pull request by phette23**
Couple different styles of doing a "past speakers" section which would probably be prominent on the conference site home page. Not totally fleshed out but I thought I would throw something together for the committee to look at on Friday.

### CODE REVIEW

**Comment by phette23** [comment]
screenshots of the two styles:

screen shot 2015-06-08 at 9 23 41 pm

screen shot 2015-06-08 at 9 23 48 pm

**Comment by sdellis** [comment]
Wow, @phette23, I have to apologize that I did not see this pull request.  Thanks for adding this.  I was thinking circles, which seem to be [quite the rage](http://aneventapart.com/event/austin-2015), but we should discuss this with the group.

**Comment by cdmo** [comment]
FWIW I like style 2 better

**Comment by queryluke** [comment]
I used circles when creating the presentation page. But I can switch to whatever. I like style 2 as well. Maybe style 2 but with circles as well?

**Comment by phette23** [comment]
We don't really need this sitting around anymore, closing.

**Pull request closed without merging**
