### PR TITLE
Speakers

### PR DESCRIPTION
**Pull request by sdellis**
Fixed modals.

### CODE REVIEW

**Comment by sdellis** [comment]
@jtidal What's going on with this Speakers.html page?  I fixed a bunch of stuff, including the modals, and submitted a pull request ([here's what I did](https://github.com/code4lib/2016.code4lib.org/commit/2139e642334f19965eee11e8daeb380e888c13fc)).  Instead of reviewing and merging the pull request into master, did you continue to work on the speakers branch?  Now it's got conflicts.  Can you take a look and make it right?

**Comment by queryluke** [comment]
@jtidal Additionally, which past speakers are you using? For the placeholder schedule page, my plan is load the list of past speaker presentations (all keynotes and any other prominent speakers) into a single timeline.

@sdellis Is there any information about which past presentations were particularly interesting? Or should I just cherry pick from the previous conference pages?

**Comment by sdellis** [comment]
Yeah, it makes sense to be consistent, and it would be good to have a sample of talks from recent years.  If that's the direction we want to go (which I like), We want to make sure people know this is a sample from previous years, and not the lineup for this one. The goal is to give both sponsors and newcomers an idea of what we have been focusing on. (PS - I will be away camping most of this week and may not respond right away.)

**Comment by sdellis** [comment]
@jtidal let us know if you're having trouble merging or anything. We'll work it out!

**Comment by jtidal** [comment]
Oops, yes, I updated the speakers page after getting @sdellis updates. 

I'm also out this week until the 25th and my work is on my office workstation. When I get back, I imagine I can revert back to the previous version? 

@roastduckalamode The speakers I was using were the ones that were in the data file.

**Comment by queryluke** [comment]
@jtidal No problem. I'll come up with a list of past speakers/presentations that we can both work from.

**Comment by sdellis** [comment]
@roastduckalamode Actually, we will need some past speakers for the prospectus too.  Not sure if you want to take a stab at using the ones from the last page of the prospectus, but that's the last to-do part of the prospectus template.  (See my pull request #41 )

**Comment by sdellis** [comment]
Ok, so I take it this is not the page you want @jtidal :
http://code4lib.github.io/2016.code4lib.org/speakers.html

If there is a previous version you'd rather use, can you send me a link and I'll merge it?

**Comment by jtidal** [comment]
Whoa! Yeah, that's totally not the right one. 

We'll want to use this one: https://github.com/code4lib/2016.code4lib.org/blob/speakers/speakers.html

> > > Shaun Ellis notifications@github.com 8/25/2015 3:57 PM >>>
> > > Ok, so I take it this is not the page you want @jtidal :
> > > http://code4lib.github.io/2016.code4lib.org/speakers.html 

If there is a previous version you'd rather use, can you send me a link and I'll merge it?

---

**Comment by sdellis** [comment]
Ok, thanks!  I will merge tonight or in the morning.  :)

**Comment by queryluke** [comment]
@sdellis I'm a tad confused. I didn't see any speakers in [prospectus.html](https://github.com/code4lib/2016.code4lib.org/blob/master/prospectus.html). However, in my latest work on the schedule, I put in all of the keynote speakers from the previous conferences in the [speakers.yml file](https://github.com/code4lib/2016.code4lib.org/blob/master/_data/speakers.yml). Is that enough or do you need others?

**Comment by sdellis** [comment]
@roastduckalamode I saw that, and yes, that will work!  :+1:

**Comment by queryluke** [comment]
@sdellis looks like the last 2 things is to get the speaker data injected into the speakers.html page and have links between the speaker and schedule pages. I can tackle this tonight if it can wait until tomorrow.

**Comment by sdellis** [comment]
@roastduckalamode That would be awesome and it can wait until tomorrow!  I wasn't sure what the vision was there and figured it would shake out in an "in-person hangout" pre-release "critique" that we should have soon (see my recent email).

**Comment by queryluke** [comment]
@sdellis No problem. I'll finish it up using the basic table that's there now and have a pull request by tomorrow. Then any improvement requests can happen in the hangout.

**Pull request merged**
