### PR TITLE
adds basic search functionality

### PR DESCRIPTION
**Pull request by sdellis**
@queryluke or @bibliotechy (or anyone) want to test it and do a merge?

Currently indexes on Title, Speakers-Text, and Type fields.  Full-text search is a work in progress.  I added the transcripts in the "talks" folder, but did not have the time to slice them up and add them to the _posts yet for indexing.

One thing stumped me: 
Some _posts did not have a speakers-text value.  Is there an easy way to get that value in there, or was that done by hand?

### CODE REVIEW

**Comment by bibliotechy** [comment]
First off Shaun - this is super awesome!!!!!

Now, to be picky...I searched for "digital" and I got back a weird result: `people, their digital stuff, and time: opportunities, challenges, and life-logging Barbie`  which linked to http://localhost:4000/presentation/people-their-stuff-and-time/ which has the title and slides, but no description, and no indication that it is a previous keynote (I think). 

**Edited:** Add a commit that filters the search to only posts from 2016.

**Comment by bibliotechy** [comment]
I think trying to go back to search results after you have followed one doesn't work great, but I also don't think that is a huge problem. Just having native search on a static site is more than I expected.

**Comment by sdellis** [comment]
Ah, yes, I was thinking about how to deal with the search results since it is not a page.  I think we can deal with that in the next iteration (full-text!). 

As for the weird search result, yes, I will only index items from the current year before merging this.

Thank you for giving it a spin!

**Comment by bibliotechy** [comment]
Sounds good. And just to be clear, the commit I added already limits indexing to items from 2016.

**Comment by queryluke** [comment]
@sdellis This is incredibly awesome!!!

I'll have time to take a closer look tonight. But today I'm swamped with meetings. 

For the speaker issue, the quick fix is to combine what's left in speakers_temp.yml and speakers_dummy.yml into speakers final.

speakers_temp is the list of workshop leaders that did not give bios.
speakers_dummy is the same, but for talks

However, when combined, these speakers will show up on the speakers page. To counteract this, we'll need to put in another bit variable. It might be best to continue to work on the [master speaker Sheet](https://docs.google.com/spreadsheets/d/1KZjkOXYOybheOPC7h5dFLYfNHdiV29ENUK_hhpwOyis/edit?usp=sharing), which I just shared with you two. I.e., go through speakers_dummy, and speakers_temp, adding entries into the Sheet and setting the last column (show) to 0. I'll get to this tonight, add the logic on the speakers page and reimport a final list.

Additionally, you could probably delete all the past keynote _posts, as they a no longer anywhere on the site.

**Comment by sdellis** [comment]
Wow, you guys are on it! :+1: 

Since @bibliotechy added a fix to only index the 2016 talks, I think we can leave those older ones in there for now.  I would like to pass this off to next year's web committee with as many content options as possible.

@queryluke thank you for the explanation of what needs to happen. That sounds good, and I will wait until you have a chance to tweak it tonight before doing anything further.

**Comment by queryluke** [comment]
@sdellis @bibliotechy Ok, my changes are made if you want to check them. I ran through 10 random searches and all speakers are showing up.

I had to adjust the search_data.json file creation a bit to point at the speaker_final.yml file. To get it to format correctly (i.e., appropriately placed commas) was a bit fugly on the code side of things. There may be a better way to do it, but it was what I could come up with quickly.

**Pull request merged**
